version: 2
jobs:
  build:
    docker:
      - image: clojure:tools-deps

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -R:check:test -Stree

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run:
          name: check
          command: clojure -A:examples:check src examples

      - run:
          name: test
          command: clojure -A:test

      # - run:
      #     name: test coverage
      #     command: |
      #       clojure -A:test:coverage
      #       bash <(curl -s https://codecov.io/bash)
